#!/usr/bin/env python

import math
import rospy
from sensor_msgs.msg import JointState
from std_msgs.msg import Header
from articulating_hand.msg import ServoArray, ServoDrive

class Convert(object):
    def __init__(self):
        rospy.init_node('update_joints')           # initialize node

        # get values from parameter server
        # individual servo limits
        self.servo_limits = rospy.get_param("servo_limits")
        # joint limits
        self.finger_limits = rospy.get_param("finger_limits")
        self.thumb_limits = rospy.get_param("thumb_limits")
        # joint names
        self.joint_names = rospy.get_param("joint_names")
        # initial joint angles
        self.joint_pos = [math.pi*a for a in rospy.get_param("joint_inits")[0]]

        # initialize publisher
        self.move_joint = rospy.Publisher('joint_states', JointState, queue_size=10)
        # initialize subscribers
        # FIX TOPIC TYPE AND CALLBACK FUNCTION
        self.servo_command = rospy.Subscriber('servo_cmd', ServoArray, self.create_jointstate)

        # 50 Hz publishing rate
        # self.rate = rospy.Rate(50)

        self.create_init_state()

    def create_init_state(self):
        rospy.sleep(1)                  # wait 1s before starting

        init = JointState()             # initialize JointState message
        init.header = Header()          # initialize Header component of JointState

        init.header.stamp = rospy.Time.now()    # timestamp
        init.name = self.joint_names            # joint names
        init.position = self.joint_pos          # initial joint positions
        init.velocity = []                      # joint velocities (none)
        init.effort = []                        # applied forces (none)

        self.move_joint.publish(init)   # publish message

    # FIX THIS FUNCTION TO DEAL WITH ServoArray INSTEAD OF ServoDrive
    def create_jointstate(self, command):
        state = JointState()                # initialize message to publish
        state.header = Header()             # initialize header component

        state.name = self.joint_names       # joint names
        state.velocity = []                 # joint velocities (none)
        state.effort = []                   # applied forces (none)

        for i in range(len(self.joint_names)):

            joint = command.srv_comms[i].servo_num           # joint number (i.e. array index)
            srvpos = command.srv_comms[i].servo_pos          # servo position command

            # convert from servo position to joint angle
            joint_angle = self.converter(joint, srvpos)

            # update joint position vector
            self.joint_pos[joint] = joint_angle
            state.position = self.joint_pos

        # message time stamp
        state.header.stamp = rospy.Time.now()

        #publish angle to /joint_states
        self.move_joint.publish(state)

    def converter(self, joint, position):
        if joint == 8:                  # use CMC joint limits if relevant
            joint_lims = [math.pi*x for x in self.thumb_limits]
        else:                           # otherwise use finger joint limits
            joint_lims = [math.pi*x for x in self.finger_limits]

        # servo limits for relevant joint
        srv_low = self.servo_limits[joint][0]       # lower limit (i.e. fist)
        srv_high = self.servo_limits[joint][1]      # upper limit (i.e. open hand)

        # linear mapping from servo position to joint angle
        M = (joint_lims[0] - joint_lims[1])/(srv_high - srv_low)
        B = joint_lims[0] - M*srv_high
        angle = M*position + B

        return angle

def main():
    Convert()                       # call class
    # rate = rospy.Rate(50)           # 50 Hz execution rate
    # while not rospy.is_shutdown():
    #     rate.sleep()
    rospy.spin()

if __name__ == '__main__':
    try:
        main()
    except rospy.ROSInterruptException:
        pass
